version: '3.8'

services:
  db:
    image: mysql:8
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: simple_api_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql  # Persisting data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql  # SQL script for initialization
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: node-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: simple_api_db
    command: sh -c "node dist/index.js"
    ports:
      - "3000:3000"

volumes:
  db-data:
