name:  Local Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: powershell allow...
        # shell: cmd
        run: ls
      # - name: check powershell version
      #   run: $host.Version      
      # # Add your custom build steps here
      # - name: Run Node.js build
      #   run: |
      #     # npm install
      #     # npm run build
      #     echo "Run OK"
