name:  Local Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Docker build and push
        run: |
          docker login -u alanduarte -p ${{ secrets.DOCKER_KEY }}
          docker build -t alanduarte/simple-api-rest:tagname .
          docker push alanduarte/simple-api-rest:tagname

      - name: Helm apply
        run: helm upgrade --install nodejs-app ./simple-api-rest/ --namespace develop
